package com.ssm.mapper;

import com.ssm.entity.DataControl;
import com.ssm.entity.DataControlCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DataControlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_data_control
     *
     * @mbggenerated
     */
    int countByExample(DataControlCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_data_control
     *
     * @mbggenerated
     */
    int deleteByExample(DataControlCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_data_control
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_data_control
     *
     * @mbggenerated
     */
    int insert(DataControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_data_control
     *
     * @mbggenerated
     */
    int insertSelective(DataControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_data_control
     *
     * @mbggenerated
     */
    List<DataControl> selectByExample(DataControlCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_data_control
     *
     * @mbggenerated
     */
    DataControl selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_data_control
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DataControl record, @Param("example") DataControlCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_data_control
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DataControl record, @Param("example") DataControlCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_data_control
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DataControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_data_control
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DataControl record);
}