server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/react_study_mysql?useUnicode=true&useSSL=false&characterEncoding=utf-8&zeroDateTimeBehavior=round
    username: root
    password: react_study_mysql
  jackson:
    serialization:
      INDENT_OUTPUT: true
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
shiro:
  login-url: /login
  realm: com.itmuch.react.security.jwt.JwtRealm
  filter-map:
    jwt: com.itmuch.react.security.jwt.JwtAuthenticationFilter
  filter-chain:
    jwt: ['/users/**']
    anon: ['/register','/**']



